### ISSUE TITLE
F9/F11 list scrolling doesn't always work

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-rom-public#1]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920353
 - Core Commit: bdeeb15

Sometimes F9/F11 produce gibberish instead of scrolling through the Basic listing. Ctrl-P and Ctrl-V still work 

**To Reproduce**
1. Type/paste in the full colour sprite mode example program in sprite appendix of the MEGA65 book.
2. Type LIST
3. Press F9

**Expected behavior**
The screen should scroll through the program listing.

**Screenshots**
![20220525_170034](https://user-images.githubusercontent.com/1001548/170298159-b51d3d5b-a2b5-46eb-ae7a-db5f3df091a3.jpg)

**Comment by Edilbert** [comment]
The program is not intended to be run as standalone program, but to be inserted as a subroutine in another program.
It pokes to the address AD, which is not defined in the subroutine, but must be preset by the caller.
I assume, that AD was not set to a correct address for sprite memory ($600 - $7FF), but to an address, which holds the key assignment strings. Then the key assignment strings for F9 and F11 ( F9 = Ctrl-P and F11 = Ctrl-V ) may be overwritten by the sprite data and then produce garbage, if pressed.

**Comment by fredrikr** [comment]
AD is set to 4096 in the program.

![image](https://user-images.githubusercontent.com/1001548/170574311-7c444569-961b-4a88-ae43-11bc12fea6cb.png)

**Comment by Edilbert** [comment]
The address range $1000 - $10ff is used to store the function key assignments
So poking the data to $1000 does indeed destroy the assignments.
-------------------------------------------------------------------
```
number_fkeys   = 16  ;max of 14 prog. fn. keys
_pky_lengths   = $1000  ;table of prog. fn. key sizes
_pky_buffer    = _pky_lengths+number_fkeys ;actual buffer
```
-------------------------------------------------------------------

**Comment by fredrikr** [comment]
Thanks for the feedback! This is not a ROM issue then, and can be closed.

**Comment by Edilbert** [comment]
I have not the access rights to close the issue.
I think, you as the author has to close it.
