### ISSUE TITLE
BLOAD prints start and end addresses in immediate mode

### ISSUE THREAD

**Issue by HovKlan-DH** [MEGA65/mega65-rom-public#10]
Just alike the _Final Cartridge 3_ then it would be very easy/beneficial for the user, if the MEGA65 ROM would show the address FROM-TO when doing a `DLOAD` of a file. This has the benefit of being a one-key approach and it will show valuable information of the file.

It could work like this (same way as FC3):

1. Do a directory listing
2. Go to the line/file you want to load and press `F5` - it will now put `DLOAD` at the beginning of the line and load the file and show the affected FROM-TO memory. No need to set `:` at the end
3. `DLOAD` on a blank line (F5) will be the same as `LOAD "*",8,1` - it will not `RUN` the file

E.g. loading music or a charset in to memory, then you easily can see where it loads it in to memory.

I know there are some alternatives - e.g. `\` at the beginning of the directory listing file line, but then you also need to press `ENTER` and it will not show the memory address.

I fully understand this is just another feature request and that it is not on the top of the list, but I really loved that functionality with my FC3 and it was very helpful developing stuff (and easy to use - I am lazy) :-) I also previously have suggested this on Discord, but would rather have the feature request visible here to track if this will ever happen.

Sorry for the bad picture quality from my C64 with FC3, but you get the point:
![unknown](https://user-images.githubusercontent.com/74433222/171271539-1d82a9e7-db28-49fb-ad80-7afc138630c1.png)

**Comment by dansanderson** [comment]
We should confirm that DLOAD fully honors the PRG address. It is documented to do so, but I had a recent experience that suggested it doesn't.

I know BLOAD honors the PRG address, though BLOAD should not print messages because it is used from BASIC programs.

**Comment by sir-lazarus** [comment]
BLOAD  and DLOAD shows, in immediate mode, drive number and filename.
E.g.  DLOAD "MYPRG",U8
prints on screen
LOADING 0:MYPRG
If DLOAD is used in the basic program, no loading message is printed. So it would be nice to add start and end address information to the instant load message (immediate mode).

**Comment by dansanderson** [comment]
I confirmed that DLOAD always ignores the PRG address and loads to top of BASIC, by design. I think this reduces the need to print addresses. I can still see some value in displaying the end address, but this will always be $2001 + the byte size of the program.

I'm still modestly reluctant to change the message because it's only really useful to the person who wrote the program, and a distraction otherwise. I'll ask around for other opinions. :)

**Comment by sir-lazarus** [comment]
Yes, for the DLOAD command, this information is not necessary. For the BLOAD command, however, it makes sense from my point of view. For example, if I load a non-basic program, I don't know its start and end address. However, if I want to view the program in the monitor, change it and then save it again, then I need this information.
Maybe  a verbose switch, which then outputs the additional information, is a good compromise.

**Comment by dansanderson** [comment]
I like the idea of having BLOAD print the start and end addresses, exclusively when used in immediate mode. As long as it's silent when run from a program, I don't think it needs to be a switch. 👍

**Comment by lgblgblgb** [comment]
Btw, I would be happy to always see LOAD/DLOAD/BLOAD addresses to be printed, even if it's trivial (in case of DLOAD), it's still more consistent, and useful (ie, to judge the size of program loaded for example ...). Of course, only in immediate mode, for sure! Also looks "more cool" with extra info ;) I know, it's a useless measurement of a feature though ...

**Comment by dansanderson** [comment]
Glad for the upvote! I admit my hesitance is mostly because I grew up with the C64 and wanted to keep the user experience familiar. It's obviously useful to programmers to see the addresses, and could be a good invitation to users to learn more about the computer.
