### ISSUE TITLE
Strange slowdown in drawing CHAR text in Hungry Dino game

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-rom-public#107]
**Test Environment (required)**
 - Platform: Issue occurs in xemu and hardware, so don't feel it relates to core version
 - ROM Release:
   - 920390 - issue occurs in this rom
   - 920385 - issue was introduced in this rom
   - 920384 - issue does not exist in this rom

**Describe the bug**
While playing the 'hungry dinosaurs' game on a recent rom, the vector art drew fine, but the CHAR text was drawn very slowly.

**To Reproduce**
1. Run the hungry dinos game on rom 920385
2. Observe vector art drawn fine
3. After this, observe the text drawn slowly
![](https://gurce.net/Logs/images/img_2023_12_29_14_16_19.png)

**Expected behavior**
Behaviour as before in 920384, no slowdown

**Comment by dansanderson** [comment]
Interesting. I can reproduce this in Xemu but not on real hardware.

With dev core 20231214.21,fcf8cc4 with ROM 920390 in NTSC mode, text appears instantly after pic is drawn, as intended.

**Comment by lgblgblgb** [comment]
> Interesting. I can reproduce this in Xemu but not on real hardware.
> 
> With dev core 20231214.21,fcf8cc4 with ROM 920390 in NTSC mode, text appears instantly after pic is drawn, as intended.

Wow. This is a really interesting problem, pls notify me, if it turns out to be an emulation problem, though currently I have no idea how this can happen :-O Is it possible that ROM checks vsync (though that should work the same way as on the hw) or anything which may cause to delay drawing events? My only idea right now at least, or something similar ...

**Comment by lgblgblgb** [comment]
I've checked the game, what I can see by looking at the title bar of Xemu, that with newer ROMs, the CPU clock is downgraded to 1MHz at the problematic parts, while with older ROMs it stays 40.5MHz. Indeed, the diff between 920384 and 920384 ROMs indicate, there was some CPU speed setting code change between these two ROM versions. So I'm 99.99% sure, this must be the problem. If though it works on the hardware, there must be some Xemu bug here which reacts incorrectly on CPU speed settings. The ROM changelog says:

    Fix: (Requires new core) 80x50 mode no longer switches to the wrong screen memory when CPU speed changes.
    This manifested as half a screen of garbage and instability after DOS operations and the ringing of the bell (Ctrl-G)
    while 80x50 mode was active.

If this change requires a newer core, I suppose there was some core change which is not implemented by Xemu yet. @dansanderson, do you remember what change in the core this ROM change depends on? Thanks!

**Comment by lgblgblgb** [comment]
I think this may be an Xemu problem after all. I've just opened an issue there.

**Comment by dansanderson** [comment]
(I left a comment on the other issue.)

**Comment by dansanderson** [comment]
Confirmed that ROM 920391 in Xemu-next resolves this issue.
