### ISSUE TITLE
CLR TI misbehaves once after Freezer Menu

### ISSUE THREAD

**Issue by jim-64** [MEGA65/mega65-rom-public#109]
**Test Environment (required)**
 - Platform: MEGA65
 - ROM Release: 920377
 - Core Commit: DEA350F

**Describe the bug**
After exiting the Freezer, the first instance of CLR TI does not set TI to zero, but seems to set it to something around 17.

**To Reproduce**
Type in this program
`10 CLR TI : PRINT TI`
enter the Freezer and exit, then issue three RUNs
```
RUN
RUN
RUN

```
The first instance will be just over 17, all subsequent runs operate correctly.

**Expected behavior**
CLR TI should set TI to 0 every time, even if you just exited the Freezer.

**Comment by johnwayner** [comment]
@jim-64 Thanks for the tip about using the freezer to reproduce this bug.  I was able to quickly figure out the fix because of that.
