### ISSUE TITLE
Screen editor insertion mode bug

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-rom-public#116]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65 R3 
 - ROM Release: 920393
 - Core Commit: 68aabb0

**Describe the bug**
If you insert characters, and type two double quotes, you're still in insertion mode. This bug is present on the C64 as well, but maybe it can be fixed on the MEGA65?

**To Reproduce**
Type:
`10 PRINT A` (Enter)
Use the cursor keys to up to just after `PRINT` on line 10.
Press Shift-Insert twice.
Type `""` (two double quote characters)
Now press cursor down. The cursor should now move to the line below, but instead you get a reverse Q.

**Expected behavior**
I expect to leave insertion mode when I've inserted two characters and typed two characters, unless I've just typed an odd number of double quote characters.

**Screenshots**
-
**Additional context**
-

**Comment by dansanderson** [comment]
Interesting! I would concur that more intuitive behavior would be for quotes to not change quote mode while being typed in insert-quoted spaces, including the last one. It seems to be implemented this way except for just the edge case where the last inserted character is a quote. I can insert lots of characters and it doesn't matter how many quotes I type, I'm only in quote mode after the last one if the last one is a quote. Hopefully that means it's easy to fix.
