### ISSUE TITLE
RUN/STOP broken after tapping CTRL key and running BASIC loop that clears screen

### ISSUE THREAD

**Issue by rscottfree** [MEGA65/mega65-rom-public#117]
**Test Environment**
 - Platform: MEGA65 R3A
 - ROM Release: 920394
 - Core Commit: ea206f4

**Describe the bug**
```
10 print"{shift+clr home}"
20 goto 10
```

If I tap the CTRL key before typing RUN and hitting RETURN, then I can't RUN/STOP.
While the program is running: if I tap ESC or SHIFT and then RUN/STOP then it will break out of program execution correctly.

**Expected behavior**
RUN/STOP works all the time when a basic program is running.

**Comment by dansanderson** [comment]
Fixed in ROM 920395. Thanks!
