### ISSUE TITLE
MOUNT OFF: unmount the virtual disk controller from BASIC

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#123]
There is currently no way to unmount the virtual disk controller from BASIC. You can do this from the Freezer by selecting "no disk" from the disk image browser. For completeness, it would be nice to be able to do this from BASIC also.

`MOUNT OFF` and `MOUNT OFF,U8` would unmount the first virtual drive. `MOUNT OFF,U9` would unmount the second virtual drive.

This syntax is proposed to avoid creating a keyword. ("OFF" is an existing keyword.)

**Comment by snoopy-f64** [comment]
I have a comprehension problem here: Is there a practical use case for an UNMOUNT or MOUNT OFF of a D81 image? If I want to use a different image, I mount it and the previous image is replaced. For what practical reason should you unmount an image if you don't want to mount another one?

**Comment by dansanderson** [comment]
Honestly I don't know, I don't think there's a practical advantage. More than one person has requested this feature over the years so I created an item for it. I think it just feels conceptually incomplete to some people that there is a state that the virtual drive can be in that can't be reached by the user. It's a capability of the Freezer, so if it's easy to do (as in, only a few bytes of ROM code) we can add it to the MOUNT command.

**Comment by dansanderson** [comment]
... I would personally rule this as very low priority and it may not be implemented. This issue exists to gather feedback. :)

**Comment by snoopy-f64** [comment]
I have nothing against such a command being implemented. ;-)

I was just wondering why it would ever be needed. :-)

**Comment by dansanderson** [comment]
I'm going to resolve this as will-not-fix after all. A virtual drive having no image attached doesn't free the unit number for IEC serial, so there's no practical advantage.

There is a documented Hyppo call that technically could be used: `LDA #$42 : STA $D640 : CLV` detaches anything attached to both virtual drives. A `MOUNT OFF` command could call this. But it couldn't select the unit number. (This is assuming that this documented call is actually implemented and working. I haven't tested it.)
