### ISSUE TITLE
Errors after an "Overflow error" with VAL and a too big number in string

### ISSUE THREAD

**Issue by snoopy-f64** [MEGA65/mega65-rom-public#14]
**Test Environment (required)**
 - Platform: xemu
 - ROM Release: 920370

**Describe the bug**
I just ran an really "ancient" test program of mine (still for the C65 emulator) on the current ROM and always got an error.

I was able to isolate the error: It occurs when you try to convert a string with VAL, which throws an OVERFLOW ERROR because the number in the string is too big. So far, so good and correct.

However, after that no command is accepted anymore, but only SYNTAX ERROR is output, no matter for which command.

**To Reproduce**

As a test you can simply use the direct mode `A$="1234567890123456789012345678901234567890"` (press four times the kieys from 1 to 0!), then a PRINT VAL(A$), which outputs the overflow error. After that no command works anymore.

As a comparison the same on the C65 emulator with the original C65 ROM 911210, where it continues without problems after the overflow error.

**Screenshots**
![mega65_val_a](https://user-images.githubusercontent.com/66867430/174475645-4c413eb9-4857-479d-b936-c4da254a1230.png)

![c65_val_a](https://user-images.githubusercontent.com/66867430/174475648-77bd59a5-fa92-4506-b7f4-cf53d50ce5de.png)

https://www.forum64.de/index.php?thread/127057-bug-report-val-overflow-error/

**Comment by Edilbert** [comment]
Thanks for the report. V920371 fixes this issue.
