### ISSUE TITLE
ROM function LOAD ($FFD5) ignores BANK

### ISSUE THREAD

**Issue by BruderJo** [MEGA65/mega65-rom-public#148]
**Test Environment**
 - Platform: (xemu)
 - ROM Release: (920395)
 
**Describe the bug**
The KERNAL ROM routine for LOAD ($FFD5) does not load a binary file into the correct bank.
The upper 2 byte of the target address [$AD] were not initialized.
$AD,$AE = lower 16 bit address. correct initialized by .X /.Y or program's own target address (based on value in 'sa')
$AF,$B0 = were never touched and have random values

```
LF57A:
  sta     [$AD],z         ; F57A EA 92 AD   <---- load memory with byte value
LF57D:
  inw     $AD             ; F57D E3 AD  
  bne     LF583           ; F57F D0 02  
  inw     $AF             ; F581 E3 AF  

```

**To Reproduce**

```
  LDA #1                ;load to BANK1 was ignored
  JSR SETBNK

  ; this code corrects the kernal issue
  lda #0
  sta $b0  ;hi-byte = 0
  inc
  sta $af  ;lo-byte  := bank 1

; continue with loading a file

  LDA #7          ;length file name
  LDX #<NAME
  LDY #>NAME
  JSR SETNAM

  ; Datei oeffnen
  LDA #0      ;la
  LDX #8      ;fa
  LDY #1      ;sa
  JSR SETLFS

; A=0, DAHER LOAD Datei
  LDX #<BASE
  LDY #>BASE
  JSR LOAD
```

checking with MONITOR. The file is now at it's place.
If you do not insert the 4 lines to initilize $AF/$B0, the file is loaded to a random bank.

**Expected behavior**
ROM function LOAD shall be updated that it loads the BANK value into the [$AD] vector.

**Comment by dansanderson** [comment]
This has been fixed in a recent ROM beta. Please upgrade and try again. There's also a new appendix on the KERNAL APIs in the Compendium with tested examples.

Thanks for the report!
