### ISSUE TITLE
Unable to reset when PRG has a cartridge signature at $8004

### ISSUE THREAD

**Issue by godot64** [MEGA65/mega65-rom-public#15]
When a prg that is run in Mega65's C64 mode has the signature of "CBM80" at C64-location $8004 it is impossible anymore to reset the machine. After hitting the reset button, it hangs in an unpredictable state. You can only switch it off and on again. This happens from any place, even from the freezer. 

My proposal: before (or while) resetting, clear at least one of the five signature bytes.

I encountered this behavior when running TSB in C64 mode (which works flawlessly).

Arndt

**Comment by dansanderson** [comment]
I am unable to reproduce this by poking $c3,$c2,$cd,"8","0" to $8004 in either C64 mode or C65 mode. It's possible that I'm not reproducing it correctly.

I'm reluctant to change memory during a warm reset given that the intended behavior is to not modify RAM in general. For example, I would expect it to be a desirable behavior to simulate cart data in memory with a warm reset, as long as you put a valid C64 cart jump vector at $8000.

If you feel strongly that this requires a change, please re-open with more detailed justification and reproduction steps.
