### ISSUE TITLE
Same as bug 150 but with DECBIN()

### ISSUE THREAD

**Issue by Rhialto** [MEGA65/mega65-rom-public#151]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920407
 
**Describe the bug**
From code inspection in b65.src I noticed that just after the `bin2dec`: label there was the same buggy code pattern that was fixed in commit 335e2e46f1b764e79999b02e7d8acde1e9d93020.

The fix would be the same too.

**Comment by dansanderson** [comment]
Thanks! I knew I should have checked. 😅
