### ISSUE TITLE
Show current loading full filename when the file in the load command uses wildcards

### ISSUE THREAD

**Issue by sir-lazarus** [MEGA65/mega65-rom-public#155]
When a file is loading  with a given wildcard, e.g. DLOAD "MYGA*", it shows the message with the wildcard LOADING 0:MYGA*

It would be nice, if it would displays the full name of the loading file e.g. LOADING 0:MYGAME
So I know which real file is loaded afterwards.
This request also applies to other DOS commands (e.g. DVERIFY,DELETE...)

**Comment by dansanderson** [comment]
It's a nice idea but it'll be challenging to implement. The wildcard path goes to the disk device, and the disk device doesn't return the matched filename when performing the load. The DLOAD command would have to load a full directory listing and do its own wildcard pattern matching on the data that comes back. My hunch is it won't be worth the code space or the added disk activity.

**Comment by dansanderson** [comment]
... Implementing a non-DOS directory wildcard matcher would be useful for this issue: https://github.com/MEGA65/mega65-rom-public/issues/152 Still not sure we should load the directory before every DLOAD just for this, but that's something at least. :)

**Comment by dansanderson** [comment]
I'm going to resolve this as infeasible. We aren't able to change Commodore DOS at a low enough level to make this work efficiently, and doing this within Commodore DOS's existing feature set (loading the directory every time it loads a file) would add far too much delay to disk operations.
