### ISSUE TITLE
Pagination parameter for TYPE command

### ISSUE THREAD

**Issue by sir-lazarus** [MEGA65/mega65-rom-public#160]
When you list a SEQ File with the TYPE command. The contend rushes with high speed over the screen without any breaks.

Adding a parameter P for pagination to the TYPE command, would be handy.

**Comment by dansanderson** [comment]
This exists! 😊 This was added in ROM beta 920396 (one beyond release v0.96) and will be in the v0.97 release.

**Comment by dansanderson** [comment]
... The syntax is: `TYPE P "FILENAME"`
