### ISSUE TITLE
BASIC's RMOUSE command - position bug

### ISSUE THREAD

**Issue by Pimau** [MEGA65/mega65-rom-public#162]
**Formal description:**
The mouse X coordinates which are given back by RMOUSE are wrong, when the following circumstances apply:
- MOUSE ON was used with a sprite number higher than 0
- The mouse pointer is moved to a X coordinate higher than 255
 
**Tech description:**
X coordinates of sprites 1-7 are having a wrong MSB part. So the coordinate start with 0 again (in many cases) when it should be 256 or higher. There is an absolute,Y index addressing wrong which can also lead to unexpected behavior, depending on other sprite data which gets hit accidently.

**Tested HW/SW:**
- Mega65 b6
- ROMs: 920395, 920407
- Cores: mega65r6-release-0.96-3c10488, mega65r6-develo-118-d8873ce

**Way to reproduce:**
Run the BASIC prg below and move the mouse cursor to the right. See how the X coordinate becomes smaller again when you move the mouse 2/3 of the screen to the right. When you use MOUSE ON 1,0 which activates sprite 0, the function is replying correctly.

        10 MOUSE ON 1,1
        20 RMOUSE X,Y,B
        30 PRINT X
        40 GOTO 20
 
**Possible fix:**
In b65.src, line 18247 in routine "rmouse" we have:

        ldy _mouse_pointer      ;Get pointer to sprite
        lda vic,y               ;Get X position
        sta grapnt              ;lsb
        lda sbits,y
        and spr_xmsb            ;msb
        beq 20$
        lda #1                  ;convert to 0 or 1
    20$ sta grapnt+1
 
The second usage of the Y register as index (lda sbits,y) must be NOT the _mouse_pointer, BUT the sprite number. The following code would work, because the sprite number is the _mouse_pointer divided by 2:
 
        ldy _mouse_pointer      ;Get pointer to sprite
        lda vic,y               ;Get X position
        sta grapnt              ;lsb
        tya                     ;A free to use at this point
        lsr a                   ;Shift right with b7 = 0 to divide by 2
        tax                     ;Use X instead of Y for the index, 
        lda sbits,x             ;because we need Y again below
        and spr_xmsb            ;msb
        beq 20$
        lda #1                  ;convert to 0 or 1
    20$ sta grapnt+1

**Comment by dansanderson** [comment]
Verified and fixed as suggested. Thanks @Pimau !
