### ISSUE TITLE
find /rem/ gives syntax error

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-rom-public#170]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65 R3
 - ROM Release: 920395
 - Core Commit: 0915d2e
 - 
**Describe the bug**
The command `find /rem/` should find all REM statements in the code. Instead, it gives syntax error.

**To Reproduce**
1. Type `find /rem/`

**Expected behavior**
It should print all Basic lines with REM in them.

**Screenshots**
-
**Additional context**
-

**Comment by dansanderson** [comment]
This is a documented edge case. From the User's Guide:

> Due to how BASIC is parsed, finding the REM and DATA keywords requires using the colon as the delimiter: `FIND :REM TODO:` This does not work with the CHANGE command.
