### ISSUE TITLE
Source and target filename can be the same in the COPY command

### ISSUE THREAD

**Issue by jwa1974** [MEGA65/mega65-rom-public#174]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65 R6
 - ROM Release: 920395 / 920408
 - Core Commit: 3c10488

**Describe the bug**
When doing a file COPY, where source and target filenames are the same (on the same disk), no error will be issued. The copy will be done, ending up with two files with the same name. Only if copying a second time, with the same names, a "FILE EXISTS" will be issued. Also, the documentation states the names must be different.

**To Reproduce**
1. Start with a clean disk (image or internal).
2. Save a test file, eg:  `DSAVE "FILE"`.
3. Do a copy: `COPY "FILE" TO "FILE"` -> No error!
4. A DIR will reveal two files with the same name!
5. Do another copy: `COPY "FILE" TO "FILE"` -> `63,FILE EXISTS,00,00`

**Expected behavior**
The command should issue an error when source and target filenames are the same (on the same disk) the first time.

**Screenshots**
![copy_bug](https://github.com/user-attachments/assets/1e8c5a10-3ac8-4284-8700-f9e3226635a0)

**Additional context**
None.

**Comment by dansanderson** [comment]
I confirmed that this is actually a bug in the virtual disk driver, not the COPY command. Migrating this to: https://github.com/MEGA65/mega65-core/issues/842

The disk device itself is responsible for file duplications. BASIC is just issuing the DOS "C" command. This works as expected for external IEC disk drives.
