### ISSUE TITLE
SPC/TAB expects a left bracket in order to be tokenised correctly

### ISSUE THREAD

**Issue by jwa1974** [MEGA65/mega65-rom-public#177]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org/?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.

- Platform: MEGA65 R6
- ROM Release: 920408
- Core Commit: 3c10488

**Describe the bug**
A left round bracket (parenthesis) is expected for SPC/TAB in order to tokenise; i.e. "SPC(" and "TAB(". 

**To Reproduce**
Steps to reproduce the behaviour:
1. Enter a line as "10 SPC" or "10 TAB"
2. Enter a second line as "20 SPC(" or "20 TAB("
3. Inspect the highlighted text when doing a list and notice SPC/TAB is just regular text and "SPC("/"TAB(" is recognised as a token
4. Inspecting the code at $2001 and onwards in the monitor reveals the issue

**Expected behaviour**
Example given here is for SPC, but the same applies to TAB.

As of now, the token $A6 is for "SPC(" and not for "SPC". See the screenshot for a comparison between SPC and RND.
SPC( = $A6 $32 $29
RND = $BB $28 $32 $29
The tokenised SPC should probably be like the RND;
SPC = $A6 $28 $32 $29

**Screenshots**
![spc_token](https://github.com/user-attachments/assets/1d66c151-fc74-40d8-8883-32573870ab0f)

**Additional context**
Of course, all of this could be something that's been in all the older Commodore versions of BASIC, but I thought it would be good to at least raise it for a discussion. It could be a bug from the beginning, right? ;-)

**Comment by dansanderson** [comment]
Indeed this is true for all Commodore BASICs. Not a bug, just a quirk, and it should match previous Commodore BASIC tokenization when possible. Good find though!

**Comment by dansanderson** [comment]
... And actually there's a reason: SPC() and TAB() are not processed as functions like RND() and others are, they're handled in special ways. SPC() is not a function that returns a string, it's a special kind of command that only works during PRINT. You can't do X$=SPC(2), for example.
