### ISSUE TITLE
TI variable gets cleared after using RUN <line_number> command

### ISSUE THREAD

**Issue by pstankiewicz** [MEGA65/mega65-rom-public#178]
**Test Environment (required)**

- Platform: MEGA65R6
- Core Commit: https://github.com/MEGA65/mega65-core/commit/3c1048830bb6f543cb832049e969301a9a389fa2
- ROM Release: 920395

**Describe the bug**
`TI` special variable is cleared after using `RUN <line_number>` command

**To Reproduce**

1. Write simple BASIC program:
```
10 ? TI
20 FOR I = 0 TO 1000: NEXT I
20 ? TI
```
2. Run it normally using `RUN` for a couple of times, it should print increasing number of seconds (correct behavior)
3. Run it using `RUN 10` command. It always prints:
```
   4.4768486E-5
   0.039128674
```

**Expected behavior**
No matter if using `RUN` or `RUN <line_number>`, `TI` variable should not be cleared

**Comment by dansanderson** [comment]
Nice find! C65 ROM does not have this issue, so we somehow introduced it.

**Comment by dansanderson** [comment]
This was introduced in 920183 back in June 2021. https://github.com/MEGA65/mega65-rom/commit/8b5b60d3b6b5587bdff409861a3315bd674a6b70#diff-0962fe91edbf3288ab1d64a46fca05ebd2a083f6d6243f22b652b16757d12cb0R5868

These three resets were added to the "run with line number" path:

```
    jsr clearc       ;first trash all variables
    jsr Clear_TI     ;restart MHz clock
    jsr oldspc
```

This appears to be the only meaningful addition to this part of the code in this change. It's not a refactor from somewhere else, it was just added. From this, I don't see a reason why `jsr Clear_TI` is in here, and I don't see a reason not to remove it.

I'm also not sure `jsr clearc` should be here, like so:

```
10 A=999
20 STOP
30 PRINT A

RUN

BREAK IN 20
READY.
CONT
 999

READY.
RUN

BREAK IN 20
READY.
RUN 30
 0
```

I would think it common to want to start a program from the middle with the current variable state.

I will try removing both of these lines and see if it breaks anything. The commit's description refers to handling of the DS disk status built-in, so maybe that needs to be cleared explicitly.

**Comment by dansanderson** [comment]
— Correcting myself: The RUN 30 example I just tried actually has this behavior on the C64, i.e. variables are indeed reset upon `RUN <line>`. I'll stick with just removing the `Clear_TI` call for now, which should be an isolated change.

**Comment by dansanderson** [comment]
Fixed https://github.com/MEGA65/mega65-rom/commit/412c5e1af63eec9f04abc750c0c4995e8f2f8045
