### ISSUE TITLE
BS Mon thinks my PC was 02xxxx when it was actually 00xxxx, breaks "G" with no args

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#19]
**Test Environment (required)**
 - Platform: MEGA65
 - ROM Release: 920376
 - Core Commit: f55531

**Describe the bug**
When my program uses the `brk` instruction, execution stops and BS Monitor runs. The program counter (PC) register is reporting an address with a page byte of `02`, when the code is actually on page `00`. This is reported by the register display (`R`).

```
    PC   SR AC XR YR ZR BP  SP  NVEBDIZC
; 0220F9 33 13 01 00 00 16 01EF --11--11
```

Executing the `G` command without arguments is supposed to jump to the last known program counter value, the address just after the `brk` instruction, resuming execution of the program. Instead, it jumps to the address with the incorrect high byte (typically hanging the machine).

**To Reproduce**
1. `MONITOR`
2. Assemble this three line program to memory using `A 3000`:

```
A 3000  00       BRK
A 3001  EE 20 D0 INC  $D020
A 3004  00       BRK
A 3005
```

3. Execute the program from the beginning: `G 3000`
4. Attempt to resume the program after the first `brk`: `G`

This can also be reproduced with an assembled program containing a `brk` instruction.

**Expected behavior**
At step 3, the program executes then immediately re-enters the monitor. It shows the program counter is `003001`. Step 4 continues execution at that address, changing the border color then re-entering the monitor.

**Actual behavior**
At step 3 the monitor shows the program counter as `023001`. At step 4, the computer hangs, presumably because it just jumped to `023001` instead of `003001`.

**Additional information**
I can use the monitor to repair the program counter value and continue the program: cursor up to the `;` line and change the PC to `003001`, press Return, then continue execution with `G`.

I tried assembling and running a program that sets all registers to 0 and calls `map`, then `brk`. This didn't seem to fix it. I also tried the BASIC command `BANK 0` before invoking the monitor. These don't seem to be the source of the incorrect `02`.

**Comment by gardners** [comment]
Note also that a BRK instruction is actually 2 bytes long: A real 6502 will also skip over the byte following a BRK instruction.  This doesn't change that the bank number is wrong...

**Comment by dansanderson** [comment]
I've definitely read a bunch about the two-byte `brk`. BSMon assembles it to one byte, and also concludes (either on its own or what it's told by the `brk` handler in ROM) that the PC is one byte after the single-byte `brk` instruction. For what it's worth, ACME appears to assemble `brk` as one byte. Not saying that's correct, but rather we might have some unfortunate tooling disagreement.

I filed [a separate issue](https://github.com/MEGA65/mega65-rom-public/issues/20) to request research and a support decision for two-byte brk. It might be a non-issue in practice, but right now it looks like the ROM and tools treat BRK as one byte.

**Comment by dansanderson** [comment]
Fixed in ROM 920378.
