### ISSUE TITLE
Problems with POKE B and POKE W

### ISSUE THREAD

**Issue by snoopy-f64** [MEGA65/mega65-rom-public#2]
When POKE is used in conjunction with variable names that begin with B or W, mostly undesirable side effects occur.

The problem came to the attention of a user by chance, because he wondered why PRINT BF(BZ) works in his program and outputs 2594, but a POKE BF(BZ),1 does not put a 1 in the place of 2594. However, a POKE 2594,1 does work. 

https://www.forum64.de/index.php?thread/118911-der-mega65-laber-stammtisch/&postID=1843717#post1843717

The reason is that POKE interprets the B of BF as a "POKE byte" and thus undesirably executes POKEB F(BZ),1.

The problem also occurs with variable names that begin with W because of POKE W.

![pokebw_a](https://user-images.githubusercontent.com/66867430/170517200-8e3b720e-bfef-4788-b234-51b2d718bf70.png)

The line POKE WF,65 lets **crash** the system!

![pokebw_b](https://user-images.githubusercontent.com/66867430/170517230-aa70338f-bd62-4889-a21d-f9a82a7cda1b.png)

For most people it will be not clear, why line 40 sends a syntax error, but line 20 not?

**Comment by EgonOlsen71** [comment]
Something similar applies to the corresponding PEEKW/B-Functions. This code should give you 128 read from memory location 5000, but it gives you 320 read from 1000/1001 instead:

`
10 DIM W(1000)
20 POKE 1000,64: POKE 1001,1
30 POKE 5000,128
40 W(1000)=5000
50 PRINT PEEK W(1000)
`

**Comment by Edilbert** [comment]
If you want to peek the contents of W(1000), the above syntax is wrong.
All functions require an opening parenthesis '(' after the function name, so you can write
PEEK(arg) or
PEEKW(arg) 
but never write the argument directly after the keyword.
so line 50 would be correct:
50 PRINT PEEK(W(1000))

**Comment by EgonOlsen71** [comment]
> If you want to peek the contents of W(1000), the above syntax is wrong.

True, I guess I was confused by the whole issue, which is something that others might be as well when looking at code like PEEK W(1000) thinking that it should be wrong just as PEEK V(1000) would be. I would still prefer to this gets changed to something like WPOKE/WPEEK instead, which wouldn't suffer from these issues.

**Comment by lydon42** [comment]
Fixed in V920356 by renaming POKEW -> WPOKE and removing POKEB (just use POKE).
