### ISSUE TITLE
Change name in the startup display of the stable ROM

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-rom-public#22]
We want to change the displayed name from
`THE MEGA65 DEVELOPMENT SYSTEM`
to something else, so it becomes clearer that this is the stable ROM.

Also the copyright notice needs to be changed to 2022.

Current contenders are:
`THE MEGA65 PERSONAL COMPUTER SYSTEM` (like C64C)
`THE MEGA65 MICRO COMPUTER SYSTEM`
`THE MEGA65 HOME COMPUTER SYSTEM`

**Comment by oe4dns** [comment]
THE MEGA65 HOME COMPUTER SYSTEM - sounds great :)

**Comment by dansanderson** [comment]
Steering Committee decision: "THE MEGA65 PERSONAL COMPUTER SYSTEM"

```
diff --git a/b65.src b/b65.src
index ccc37ee..8c9774e 100644
--- a/b65.src
+++ b/b65.src
@@ -1362,7 +1362,7 @@ signon_message
    .byte code_clr
    .byte code_rvs,code_red,'                     ',code_rof,code_tri,code_cr
    .byte code_rvs,code_ora,'                  ',code_rof,code_tri
-   .byte code_def,code_tab,'     THE MEGA65 DEVELOPMENT SYSTEM',code_cr
+   .byte code_def,code_tab,'  THE MEGA65 PERSONAL COMPUTER SYSTEM',code_cr
    .byte code_rvs,code_yel,'               ',code_rof,code_tri,code_cr
    .byte code_rvs,code_grn,'            ',code_rof,code_tri
    .byte code_def,code_tab,'     (C) 2021 MEGA, 1991 COMMODORE, 1977 MICROSOFT',code_cr
```

![mega65-screen-000032](https://user-images.githubusercontent.com/408973/189445400-b9ad94e3-7dac-43fc-b96f-516f3092594c.png)

**Comment by lgblgblgb** [comment]
Btw, `2021 MEGA` shouldn't be modified to `2022 MEGA` since a while already? At least I assume the year is the one when it was released? Or hmm I am not sure how it should be interpreted, clearly FROM-TO year is more clear but overkill here, so I would assume this way at least.

**Comment by dansanderson** [comment]
When a work contains material published across multiple years, you can either use the earliest date (2021) or a date range (2021-2022) in the copyright notice. Using only the latest date can cause confusion if a copyright is challenged or an infringement claim must be asserted. In most countries, a work is copyright the moment it is created, though typically the date of first publication is used in the notice. The notice is there to inform others of how copyright law applies to the work (e.g. duration of the copyright), and to demonstrate that an infringer was informed of the assertion of copyright. (In the US, the copyright notice was mandatory up until March 1st 1989. It is currently optional, but still has value in civil court.)

It's possible the license of the original Commodore ROM may specify additional terms that apply to the copyright notice. I'm not familiar with the license text. For all I know the additional mentions of Commodore and Microsoft are there just as a courtesy or tribute.

**Comment by lgblgblgb** [comment]
Aha, thanks, it's new for me, I always thought that the latest modification is the significant, especially if it's throughout years of development, "surely" not the 10-20 years ago is what you want to show. But hey, it seems I was wrong.

**Comment by dansanderson** [comment]
This has been implemented in 920377.
