### ISSUE TITLE
Disable display of date and time in BASIC welcome header

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#24]
Approximately 25% of r3 boards to date have issues with the internal Real Time Clock (RTC) not working. We've sunk quite a few resources into fixing or working around this issue and do not yet have a complete solution. No software depends on this feature.

The attached patch removes the date and time display from the BASIC welcome header, which is the most visible manifestation of RTC issues on affected machines. The RTC setting (working or otherwise) is still available via the TI$ and DT$ BASIC 65 variables, and is still visible in the Onboarding and Configuration interfaces. (I recommend we keep all other RTC features intact.)

[disable_datetime_header.diff.txt](https://github.com/MEGA65/mega65-rom-public/files/9669435/disable_datetime_header.diff.txt)

**Comment by dansanderson** [comment]
P.S. This patch includes two lines that I need to add to Makefile to get the ROM to build. I suggested this in a previous patch a couple of months ago but it didn't get included. I don't understand how other ROM devs are building successfully without this.

**Comment by dansanderson** [comment]
![basicheader](https://user-images.githubusercontent.com/408973/192906147-a9051cf1-74e9-4ab4-a42e-0ddaf52dc35a.png)

**Comment by dansanderson** [comment]
Issue #591 is fixed in the latest RC2 test core that will become the batch 2 factory core and recommended upgrade core for batch 1 users. I'm personally no longer motivated to have the time display removed from the BASIC banner because now I can enjoy it. :)

Argument for removing it anyway: Of the 25% of owners affected by broken RTCs, only a fraction of them will put in the effort to acquire, assemble, and install an external RTC. It's not a huge benefit to display the clock on boot because it doesn't advance if left alone. Displaying a broken clock makes owners feel bad about their device and the overall project unnecessarily. Broken RTCs are bad publicity that gets amplified by social media, despite the low utility of the RTC feature.

Argument for keeping it: It's a small benefit to display the time on boot because it confirms that the RTC is working, has a working battery, and is set correctly. It generally gives the impression that the MEGA65 is a dynamic and featureful machine. 75% of owners and owners with external RTCs can enjoy it. Owners with non-functioning RTCs will be prompted to pursue a fix and we can tell them about the external RTC option.

**Comment by lgblgblgb** [comment]
Only my _personal_ feeling: even with 100% working RTC, I found odd to see the date displayed as of course it's not updated, I would more like some other information instead, like detected hardware version, or memory info, what `INFO` command can decode as well, so there is already code for that. Also would go (IMHO!!!) nicely with the Commodore 8 bit tradition at least like C64 saying about the hardware as well, "64K RAM system" and similar. Just removing the clock without any information instead would feel kind of empty for me, at the other hand. Again, this is only my personal feelings.

**Comment by dansanderson** [comment]
I agree, other system info would be more useful and more traditional than the current RTC setting.

The minimal change of simply removing the time and date was intended for release v0.95 and I didn't want to pursue something more complex in the middle of a release cycle. Depending on how we decide the priority of addressing this, it might be better to leave the ROM as is for v0.95 and pursue a nicer banner update in a later ROM version. (As above, I'd be more excited about distributing external RTCs to affected customers than burying the feature, now that that option is implemented completely.)

**Comment by dansanderson** [comment]
I'm closing this with no change. The external RTC fix is fully feasible and we've even gone and assembled a bunch and set up an order form if anyone wants one, and documented the whole thing. Removing the date/time from the banner could still resolve the occasional confusion of expecting the clock to update in real-time on the screen, but this is not an important issue.
