### ISSUE TITLE
Abbreviated form of run - rU - returns the error "?missing file name error"

### ISSUE THREAD

**Issue by deathybrs** [MEGA65/mega65-rom-public#26]
**Test Environment (required)**
 - Platform: MEGA65, xemu
 - ROM Release: 920377
 - Core Commit: lydon says "but core does not matter here anyway, this is a ROM problem"  He did the test on real hardware.

**Describe the bug**
As written in title:

Abbreviated form of run - "rU" - returns the error "?missing file name error"

**To Reproduce**
1. Type "rU" and hit enter
2. See error
3. Profit!

**Expected behavior**
Normally, run the loaded program.  In above reproduction steps, should just do nothing.

**Comment by lgblgblgb** [comment]
Typing a simple BASIC program:
`10 rU`
Then `LIST`ing it will result in:
`10 RUNFILE`
So the abbreviated form of `rU` seems to mean `RUNFILE`. But indeed I am kinda sure `rU` worked before, and I have never seen this `RUNFILE` and what its purpose, as `RUN` itself supports the good old `RUN` but also with syntax `RUN "filename"` as well, so I am bit puzzled what's the meaning of a separated token `RUNFILE` then ...

**Comment by dansanderson** [comment]
ROM 920367 added `RUNFILE` specifically (and solely) to support the up-arrow shortcut in a directory listing. As with all newer keywords it was added to `esc_command_list`, and this is scanned before the `keyword_list`, so there is no opportunity to disambiguate the `rU` shortcut and `RUNFILE` wins. https://github.com/MEGA65/mega65-rom/commit/d0a5be31050a2088a710518d4b2197907395c14f

Given that `RUNFILE` is undocumented (it was never added to the manual) and isn't actually intended as a user-facing keyword, I recommend renaming `RUNFILE` to something that doesn't collide with `RUN` or other often-used keyword. Alternatively, we can special-case this in the tokenizer. Perhaps a good generalization would be to have a list of keywords that do not have shortcuts and so never collide with existing ones.

**Comment by dansanderson** [comment]
Based on previous discussions about how Commodore has invalidated abbreviations historically, I'm disinclined to make an exception for rU as a shortcut for RUN (which is only one more character to type). It's unfortunate that the RUN abbreviation is overridden by a keyword that's practically invisible to the user, but this is already true and counterintuitive in many cases. I don't want to change the keyword ordering based on popular opinion. We have an exception for lO for LOAD, but that's it.

I'm glad we discussed it and will continue to follow up on documenting BASIC 65 abbreviations in the manual.
