### ISSUE TITLE
Resetting PLAY parameters to defaults

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#28]
**Is your feature request related to a problem? Please describe.**
When experimenting with the PLAY command casually, it is too easy to accidentally leave voice parameters in an unwanted state, and too difficult to reset them. Directives like note duration persist across play calls, even after calling PLAY without arguments to silence all voices.

In a program, maybe it makes sense to say that the code should be defensive against inconsistent start states and always set all voice and play-system parameters, even when using what would be the BASIC default. If that's the advice, then it shouldn't impact programs to introduce a way to reset all parameters to defaults.

Without an easy way to restore defaults, the only reliable method is to reset the machine, which seems extreme. But I don't even know offhand what the string would be that resets all of the voice parameters, or the values of the default system parameters. `"O2T0U9X0M0P0QR"`?

**Describe the solution you'd like**
Introduce a new PLAY string voice directive "Z" that resets all voice parameters to BASIC defaults when encountered. `PLAY "Z","Z","Z","Z","Z","Z"` would reset all voices.

For similar purposes, introduce `TEMPO` and `VOL` variants that when given no parameters reset the `PLAY` system parameters to defaults. `ENVELOPE env` and `FILTER sid` should also reset to defaults (do they already?).

**Describe alternatives you've considered**
It might be nice for `PLAY` without arguments to also reset all voice parameters for all voices, but I'm not sure if some people are already used to it not doing that when experimenting with PLAY strings. If this isn't intrusive for current users, this might be worth doing. A "Z" directive might still be useful as a shorthand for resetting all parameters in the middle of a string.

I wonder if it would be intuitive to reset all parameters at the beginning of every string! Require every string to either assume the power-on defaults or set the parameters explicitly. This is more aggressive but possibly encourages good coding practice.

**Additional context**
This came up when testing example PLAY commands in documentation. An example command isn't likely to include every parameter, and the reader might not know how to reset previously changed parameters and get confused when later commands misbehave (e.g. use whole notes because the last example ended on a whole note).

**Comment by gurcei** [comment]
Of the options, having the parameterless PLAY reset more things to defaults sounds good to me. I had hoped to do more resetting of stuff in it one day, but my mind just got cold and forgetful on making rom changes.

I'm not too keen on resetting upon every new string, as there's already songs I've got that will break if something like that happens.

As for a 'Z' directive, I guess I dont mind it, though maybe I just havent had a craving for a per-channel, mid-string reset capability.

**Comment by dansanderson** [comment]
Agreed. On further thought I think parameterless PLAY is more often used interactively, and when used in a program shouldn't be surprising if it resets more stuff. A "Z" directive is a half measure and probably not that useful.

**Comment by dansanderson** [comment]
When I wrote this I don't know why I didn't realize that PLAY without arguments already does this. Maybe I was just thinking through the implications of persistent parameters and it didn't occur to me to check. :P Resolving.
