### ISSUE TITLE
Enhancement(s) to USING command in BASIC 65

### ISSUE THREAD

**Issue by tonedef71** [MEGA65/mega65-rom-public#29]
Could `USING` be enhanced to support the zero-prepend option found in C?
For example, the BASIC command  `PRINT USING "%03d";7` would print `007` on the console.

I also think it would be useful if `USING` could also be leveraged independently of `PRINT` for assigning formatted values to a string variable.
For example, `HX$="$%4X":A$=USING HX$;65000: REM A$="$FDE8"`

**Comment by dansanderson** [comment]
Zero padding for %-patterns in PRINT USING is now implemented. `%0<width>[.<precision>]<type>` enables left zero padding for positive floats and integers. If the argument is negative, zero padding is cancelled (similar to printf). Hex is always left zero padded.

With apologies, I'm going to punt on the request for USING string expressions. It's a great idea but would require too big an overhaul, unfortunately.
