### ISSUE TITLE
Hypervisor, config, and core using "Enhanced" DVI video mode?

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#4]
**Test Environment (required)**
 - Platform: MEGA65
 - ROM Release: 920355
 - Core Commit: bdeeb15

**Describe the bug**
The "Enhanced" (sound enabled) DVI video mode does not work with DVI-only displays, which is why it is an option in the configuration. However, it appears that several of the pre-config menus, including the Hypervisor, core menu, and the config menu itself use "Enhanced" mode. This breaks these screens on DVI-only displays, and prevents the user from accessing the config menu to change it for the rest of the machine.

As I understand it, DVI-only mode should show a correct picture on all displays using the DVI output, including modern HDMI displays that otherwise support sound. Hypervisor et al should use DVI-only mode.

**To Reproduce**
1. Connect a DVI-only display. I'm using a Dell 2001FP and an HDMI-to-DVI video cable.
2. Hold Alt, then turn on the MEGA65.

**Expected behavior**
The Hypervisor Alt menu should display correctly. Instead, it behaves as if in "Enhanced" video mode.

The only workaround I know is to connect a VGA display to access these menus. It so happens that the Dell 2001FP has both VGA and DVI inputs, so I keep both connected and switch between them as needed. I now realize that this would not be necessary if these menus used DVI-only mode.

**Comment by lydon42** [comment]
This is a core problem, created an issue there.
