### ISSUE TITLE
Toggle 80x50 mode with F1 and Esc+x

### ISSUE THREAD

**Issue by rscottfree** [MEGA65/mega65-rom-public#44]
**Describe the solution you'd like**
Hitting `F1` or `escape+x` could toggle to 80x50 text mode in addition to the 80x25 and 40x25 modes it currently toggles.

**Describe alternatives you've considered**
Remaining satisfied with `escape+5` to toggle to 80x50 mode.

**Additional context**
I mostly bring this up because the functionality and documentation feels incomplete when we say there is an 80x50 text mode, but the button that toggles text modes doesn't include this one. In practice, I probably wouldn't use these buttons to toggle to 80x50 text mode just as I don't use them to toggle to 80x25 or 40x25.

**Comment by dansanderson** [comment]
The current behavior is that 80x50 mode doesn't participate at all in the "toggle:" if 80x50 mode is active, ESC+X (the default definition of the F1 soft key) has no effect. ESC+X could be updated to cycle through the three modes. I don't know if or how anyone might be dependent upon the current behavior.

**Comment by dansanderson** [comment]
This is currently on the same call path as the SWAPPER KERNAL routine at $FF65, and exhibits some previously unnoticed misbehavior when called in 80x50 mode. The simplest change would be for SWAPPER and ESC+X to go from 80x50 to 80x25, then toggle between 80x25 and 40x25. This isn't the change requested in this issue (to cycle modes), but it's the simplest change that handles an edge case and most closely matches previously defined behaviors.
