### ISSUE TITLE
LIST P cuts off first program line w/ 23 lines of code

### ISSUE THREAD

**Issue by Akira-Hojo** [MEGA65/mega65-rom-public#5]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920356
 - Core Commit: bdeeb15

**Describe the bug**
When making a program with exactly 23 lines and PAUSED LISTING it. The top line will not be listed as the ready prompt scrolls the screen.

**To Reproduce**
1. Make a program with 23 lines
2. LIST P

**Expected behavior**
Listing pause to show the first line

**Screenshots**
https://cdn.discordapp.com/attachments/805252939593416705/980001482831200276/unknown.png
https://cdn.discordapp.com/attachments/805252939593416705/980001637995262002/unknown.png

**Comment by Edilbert** [comment]
Fixed in 920358 - thanks for the report.
