### ISSUE TITLE
Improve RENUMBER "crunch space" call syntax

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#50]
**Is your feature request related to a problem? Please describe.**
There is currently a feature of the `RENUMBER` utility command where you can request that it remove space characters before line numbers in the BASIC source as part of its transformation of the code. (Technically it is removing trailing spaces after the keywords that can be succeeded by line numbers.) The user activates this "optimisation mode" by omitting the space between the `RENUMBER` keyword and its first argument: `RENUMBER100,10` (optimisation mode) vs. `RENUMBER 100,10` (non-optimisation mode).

No other BASIC command uses omitting a space after the keyword to request a change in behavior. Many people like to minimize keystrokes when entering commands and assume they can omit this space in general. At least two people have said they activated `RENUMBER` "optimisation mode" accidentally.

(Ironically, the "optimisation" of removing whitespace after keywords is only possible because whitespace is mostly insignificant in BASIC syntax. Introducing a command where whitespace is significant contradicts this general principle.)

**Describe the solution you'd like**
Replace the `RENUMBER100,10` calling syntax with a named flag parameter. Per other commands that have introduced one-character flags (such as `LIST P 1000-2000`), introduce a `C` option (for "crunch") that appears before the optional `RENUMBER` parameters:

```
RENUMBER C 100,10
```

The default is to not delete whitespace during processing. The previous syntax is no longer supported. `RENUMBER100,10` is equivalent to `RENUMBER 100,10`.

**Describe alternatives you've considered**
`C` for "crunch" is just a first suggestion. `O` for "optimise" might be ok, though I'm not fond of implying that this mode actually optimises anything. `O` might be easily confused with `0` (zero).

Crunching BASIC programs is a popular idea regardless of its effectiveness. I wonder if BASIC 65 would benefit from a dedicated `CRUNCH` command that knows how to remove all non-syntactic whitespace from a program. It's a destructive enough action that it deserves an `ARE YOU SURE?` prompt. If we had such a command, maybe there'd be less interest in a crunch mode for `RENUMBER`.

**Additional context**
The justification provided in the manual is to make the BASIC code more time and space efficient, but this has [no practical impact running at 40 MHz](https://dansanderson.com/lab-notes/mega65-game-of-life/), especially considering that this feature only removes a few of the spaces in the code and not all of them. One justification that occurs to me, but doesn't seem to be the documented motivation of the feature, is that `RENUMBER` can potentially cause a line to be rewritten longer than 160 characters. Asking it to remove a bit of whitespace reduces (but does not eliminate) the chance of this happening.

I had casually suggested in the Discord that we remove this feature, but several people who were around when this feature was implemented said it was requested and hard-won at the time. So far I haven't heard that anyone is particularly wedded to the "omit the space" calling syntax. It's an immediate mode-only command so changing it won't break programs.

---

Flag parameters are a new API convention introduced to BASIC 65 by MEGA65 (IIRC), and are not rigorously specified. For example, they are separate from optional positional arguments indicated by commas. This may be sufficient as a sort of API style spec:

```
<command> [<subcommand>] [<flag> [<flag>...]] [<arg> [,<arg>...]]
```

... where `<flag>` is a single letter, and `<arg>` can in some cases be a "keyword" argument that begins with a single letter. There is already a rare inconsistency in the API where a "keyword" argument without a value acts like a flag, and there are even cases where a flag and a valueless arg use the same letter, e.g. `DIR W` vs. `DIR "...",W` In the implementation, it's up to the keyword to parse its own arguments and handle ambiguities, and many arg parsing behaviors are not generalized.

There's no point in changing any existing commands, and we're unlikely to add many new ones. It's just something to consider if we make any more API clarifications, such as `RENUMBER C ...`

**Comment by vrcoderyt** [comment]
Good👍
