### ISSUE TITLE
KEY register misbehavior in ROM 920383

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#51]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920383
 - Core Commit: 93d55f0

**Describe the bug**
Knocking the KEY register (53295) with 71 then 83 to enable VIC-IV I/O mode while in MEGA65 mode misbehaves in ROM 920383. It does nothing (as expected) in ROM 920377.

Performing this knock when already in MEGA65 mode isn't particularly useful (it's already enabled) but the resulting behavior has changed in a recent ROM. This might indicate a worse issue somewhere else, so it's probably worth a look.

Notably, it works as expected in C64 mode. The misbehavior only occurs in MEGA65 in a ROM newer than 920377. (I have not yet tested intermediate ROMs between 920377 and 920383.)

**To Reproduce**
1. Turn on MEGA65, in MEGA65 mode, with ROM 920383.
2. `POKE 53295,71:POKE 53295,83`

**Expected behavior**
Nothing should happen.

**Additional context**
Reported by TOS22 in [this forum thread](https://www.forum64.de/index.php?thread/135118-different-behavior-only-in-basic-when-enabling-vic-iv-in-different-rom-versions/).

**Comment by dansanderson** [comment]
I just noticed that if I do this knock in ROM 920377 then hold the cursor-down key, the screen flickers with `@` symbols. I wonder if there's some general instability with the KEY register, and it just manifests differently in the different ROMs. Maybe this is a mega65-core issue.

**Comment by lgblgblgb** [comment]
I think, it's (and it was) never safe to do this knocking in BASIC (probably it wasn't before either just new ROMs for example do something differently which "helps" to reveal the problem). Ie, an interrupt can occur between POKEs, or for example POKE in BASIC65 may use the "math registers"  which is screwed up after the first POKE. and things like that. Strictly speaking it's possible in C64 "mode" (`GO64`) as well, just maybe C64 KERNAL would not do any MEGA65 I/O "magic" as its own, so not a big deal _there_ at least.

**Comment by dansanderson** [comment]
@lgblgblgb That's a good thought, though we do describe these as POKE-able from BASIC in the User's Guide, so if that's unsafe then we should probably rewrite that section, maybe to say that it should only be knocked from assembly code with interrupts disabled, followed by an explanation of how to do this from C64 BASIC (maybe with an ML loader with DATA statements).

**Comment by lgblgblgb** [comment]
I think, in C64 mode it's mostly safe, as C64 KERNAL itself expects C64 I/O (aka VIC-II I/O) mode anyway, so it's impossible to "mess it up", however MEGA65 ROM expects VIC-IV I/O mode, C65 ROM expects VIC-III I/O mode, and during the knocking sequence, after the first POKE and before the second I/O mode is reverted back to VIC-II mode temporary by the register write, which can cause problems. Thus, it's fine to "advertise" the knocking sequence in C64 mode, just not in others. Also it make no sense to do the knocking in MEGA65 mode (or C65, in case of C65 ROM), as it's already there, in fact it's needed to be there already ...

**Comment by dansanderson** [comment]
There's already a "note" in the documentation about not doing this in C65 mode, so I'm resolving this without further changes. (Maybe we changed this recently, I don't remember.)
