### ISSUE TITLE
Pen color resets to background colour when Line and Dot functions used in the same FOR-NEXT statement

### ISSUE THREAD

**Issue by lipi650** [MEGA65/mega65-rom-public#59]
**Test Environment (required)**
 - Platform: xemu
 - ROM Release: 920377
 - Core Commit: f7554a8 (?)

**Describe the bug**
Pen color resets when Line and Dot functions used in the same FOR-NEXT statement.
The issue occurs when the line is drawn first and the dot after.
The issue does not occur when the dot is drawn first and the line after. 

**To Reproduce**
```
10 GRAPHIC CLR
20 SCREENDEF 1,1,1,4
30 SCREEN OPEN 1
40 PALETTE 1,0,0,0,0
45 FOR I=1TO15
50 PALETTE 1,I,I,15-I,8+I/3
55 NEXT
70 SCREEN SET 1,1
80 SCNCLR 0
100 PEN 0,1
105 FOR I=1TO639STEP1
115 Z= 150+(SIN(I/20)*20)
120 LINE 319,399,I,Z
125 DOT I,120
130 PEN 0,I/43+1
160 NEXT I
170 GETKEY A
180 SCREEN CLOSE 1
190 PALETTE RESTORE
```

**Expected behavior**
Both lines and dots should use the same color different from background color.

**Screenshots**
Expected: https://www.forum64.de/wcf/index.php?attachment/381072-line-dot-b-png/
Actual: Only the first few lines/dots are drawn with visible color.
**Additional context**
The issue does not happen when we swap lines 120 and 125 or when we set pen colour before drawing each dot.

**Comment by dansanderson** [comment]
Just a quick confirmation that I can still reproduce this with the program listing provided. Listing:
![pencol-listing](https://github.com/MEGA65/mega65-rom-public/assets/408973/372c19b9-cd5e-4bb9-b94e-45f2370c5841)

Faulty result:
![pencol-result1](https://github.com/MEGA65/mega65-rom-public/assets/408973/33a729ea-776e-4fad-adf1-d9bac71c7a73)

Expected result, can be produced by swapping lines 120 and 125:
![pencol-better](https://github.com/MEGA65/mega65-rom-public/assets/408973/ae08e09b-adef-4d5a-b5f1-ff7bb52689af)

**Comment by dansanderson** [comment]
Here's a simpler example that exhibits similar broken behavior:

```
10 screen 640,400,4
20 palette 0,0,0,0,0
30 palette 0,1,1,14,8
40 for i=1 to 639
50 pen 0,1
60 line i,0,i,30
70 dot i,120
80 next
90 getkey a
100 screen close
```

* DOT before LINE works.
* LINE before DOT breaks with a corrupt display after 12 iterations.
* Removing the PEN statement only draws the first loop iteration in the intended color. DOT before LINE, both draw the first in the correct color. LINE before DOT, only the line gets the intended color.
