### ISSUE TITLE
Undo HOME keystroke

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#6]
**Is your feature request related to a problem? Please describe.**
Too often, I accidentally hit the HOME key when reaching for the DEL key. I then have to struggle with cursor movements to get back to what I was doing. This feels especially fragile with a long un-entered line. (And for what it's worth, I have the same problem on Commodores. MEGA is just in a position to do something about it.)

**Describe the solution you'd like**
When I press HOME in the BASIC editor while not in quote mode, MEGA remembers the previous cursor position, then homes the cursor. If I press ESC then HOME, the cursor moves to the previously stored position.

**Describe alternatives you've considered**
A small general purpose undo-typing buffer could be interesting. I would expect it to clear after pressing Return because it can't undo commands. There might be too much state to track, and too little utility for the cost.

A home-to-bottom keystroke might reduce some of the pain of re-finding the location, without fully solving the problem if a full solution is impractical.

I briefly considered whether stored cursor positions could be more generally useful, like a cursor home ring buffer or something. Given the nature of the screen editor, I think this would have limited usefulness. But maybe just the single stored position could be used in ways other than an "undo HOME": I home the cursor to store a position, move the cursor somewhere else to do something, then ESC + HOME to restore. Again, the nature of the screen editor limits the usefulness. But it's a natural consequence of the feature as I described it.

I'm grateful for all of the BASIC 10 and BASIC 65 cursor movement options and I haven't memorized them all yet, so maybe restoring my position manually just takes some practice.

**Comment by gurcei** [comment]
Aah, I can sympathise with this situation, has happened to me many times before too (though admittedly the frequency seems to be dropping the more my fingers get accustomed to the keyboard).

A part of me wondered whether rom's behaviour could be tweaked in relation to the ESCAPE, Up (char, not cursor movement) to store cursor location and ESCAPE, left (char, not cursor movement) to restore cursor location.

These shortcuts were both intended for manual use by the user. Though I'm now wondering, could just build upon the behaviour there, and let's say, whenever the HOME key is pressed, the ROM does the equivalent of ESCAPE, up, to store the cursor position just prior to the HOME action.

That way, if the user hit HOME by accident, they could go back to where they were with ESCAPE, left char?

**Comment by dansanderson** [comment]
That's definitely what I had in mind in terms of generalizing the cursor-memory feature. I like the key suggestions! And yes I would imagine that Home would activate this feature automatically.

I'll teach myself how to build ROMs and see if there's a simple version of this I can code up. Seems like a fun ROM dev starter project!

**Comment by dansanderson** [comment]
I have a candidate implementation working.

I decided against having Home simply set the ESC-Up value because I'm concerned that it might be a common thing to store the cursor position, intentionally press Home as part of moving around, then restore the original stored position. My candidate stores the undo-Home position separately, using the same technique as ESC-Up does to keep track of homing in custom windows.

In my candidate implementation, printing a Home control code also stores the previous position. I think this is fine if the undo-Home position is kept separate. Maybe there's a better place I can trigger the save that's only for a manually typed Home key, but this does a good job of not overwriting the saved position in quote mode (because an actual Home control code isn't printed when in quote mode).

This implementation does extra work to avoid overwriting the undo-Home position when the Home key is pressed while in the home position. This prevents clobbering the undo-Home position when pressing Home twice.

**Comment by gurcei** [comment]
Looking forward to checking it out :) @lydon42 mentioned that he'd give you a ping on permission arrangements for making a PR, did he put that stuff on your radar?

**Comment by dansanderson** [comment]
Per chats with Bit Shifter and lydon, I'll just attach the diff here for now.

[6_undohome_diff.txt](https://github.com/MEGA65/mega65-rom-public/files/8799602/6_undohome_diff.txt)

* New storage for undo-home modeled after the ESC-uparrow feature: `save_home_cursor_column` et al.
* New `save_home_position` and `restore_home_position` routines, also modeled after ESC-uparrow, with one difference: save checks whether the cursor is already home and does not overwrite the previously stored position if so. (Pressing Home twice will not erase the previous.)
* `home` calls `save_home_position`. Note that this occurs when a Home character is printed, which is both the unquoted keypress and `PRINT"{rvs}S{roff}"`. I think this is acceptable, but let me know if there's a better place to put this call.
* `escape` has a new explicit check for $#13 as an escape sequence. It calls `restore_home_position`.
* Added missing rule to `Makefile` to repair a clean build.

Tested on production hardware:
* Move cursor to non-home position; press Home, cursor moves to upper left; press ESC then Home, cursor moves to previous location.
* Move cursor to non-home position; press Home, cursor moves to upper left; press Home again, no change; press ESC then Home, cursor moves to previous location.
* `WINDOW 3, 4, 40, 18, 1`, window is defined and cursor moves to new Home position; move cursor to non-home position; press Home, cursor moves to upper left; press Home again, WINDOW cancels and cursor moves to screen home.

Undo-home has a bug inside a WINDOW where ESC Home restores the cursor position offset from the original position by the WINDOW top-left coordinate. This bug is also present in the ESC uparrow feature, so it is not a regression. I can try to fix them both after submitting this change. (I can also try to fix both now if you like, just trying to keep the PR simple.)

**Comment by dansanderson** [comment]
... I'm also happy to attempt a User Guide update if/when this feature is accepted. =)

**Comment by dansanderson** [comment]
Diff after rebase with latest:
[6_undohome_diff.txt](https://github.com/MEGA65/mega65-rom-public/files/8799674/6_undohome_diff.txt)

**Comment by dansanderson** [comment]
New revision: 
[6_undohome_diff.txt](https://github.com/MEGA65/mega65-rom-public/files/8800612/6_undohome_diff.txt)

This fixes both ESC-uparrow and ESC-home to honor windows. This diff also increments the ROM version.

One tiny issue: when in a window, ESC Home then Home registers as "Home Home" and exits the window. I tried clearing `lstchr` in `restore_home_position` but it didn't seem to work. I'm leaving this unfixed for now.

**Comment by dansanderson** [comment]
New revision, merges in 920360 and is now numbered 920361:
[6_undohome_diff.txt](https://github.com/MEGA65/mega65-rom-public/files/8816209/6_undohome_diff.txt)

**Comment by dansanderson** [comment]
Resolved at ROM 920362. Thanks very much all!
