### ISSUE TITLE
MEGA65 boot state of $0000/$0001 mapping should not map any ROM, only enable I/O

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-rom-public#61]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - ROM Release: 920383
 - Core Commit: 93d55f0

**Describe the bug**
Developers targeting MEGA65 mode have little use for C64-style memory mapping, with the CPU hardware registers at addresses $0000 and $0001. The default boot state should be using this mechanism exclusively for I/O at $D000-$DFFF, setting bit 2 to 1 (%1xx) by default. Other C64 ROM mapping features are not useful in MEGA65 mode. (C65 ROM is mapped via the MAP register.)

As of ROM 920377-920383, the default boot state of $0000 and $0001 appears to be $FF. As per [C64 documentation](https://sta.c64.org/cbm64mem.html), the lowest two bits being %x11 maps in C64 ROM at $A000-$BFFF and $E000-$FFFF. This blocks access to RAM unnecessarily in these regions and causes confusion when trying to reconcile the three memory mapping mechanisms in MEGA65 mode.

The lowest two bits should instead be %01. This exposes the other address mapping mechanisms at 16-bit addresses $A000-$BFFF and $E000-$FFFF. For example, the BASIC command `BANK 0:SYS $B000` should execute an ML routine stored in RAM at 0.B000. (Note that other BASIC commands bypass C64-style mapping when `BANK 0` is issued, but not `SYS`.)

We should investigate why recent ROMs have a boot state of $0001 = $FF, and whether setting the lowest two bits to %01 breaks any known MEGA65-mode software. If it doesn't cause significant issues, we should change the ROM to set this to %01 on boot.

**To Reproduce**
1. Boot into MEGA65 mode.
2. `?PEEK(1)` : displays 255
3. `BANK 0:POKE $B000,$EE:POKE $B001,$20:POKE $B002,$D0:POKE $B003,$60` : writes an ML routine to cycle the border color to address $B000
4. `SYS $B000`

**Expected behavior**
With `BANK 0` selected, `SYS $B000` should execute the ML routine at $B000, rotating the border color by one step. Instead, it does nothing (it calls the ROM data at that address, which does nothing).

You can confirm that the C64 banking is in the way by clearing it, as follows: `POKE 1,53:SYS $B000`

**Comment by dansanderson** [comment]
Notably, the original C65 ROM 911210 boots with register 1 set to $FF. Maybe this is a feature request that needs to be tested well for compatibility with existing software. I still agree with it, as MEGA65 developers shouldn't have to worry about banking out unused C64 ROM data.

**Comment by ki-bo** [comment]
I tested several older ROMs, and even with a stock C65 ROM, the initial value in $0001 is always reported as $FF. There were reports that earlier ROMs do not map in BASIC V2 on SYS, so probably older ROMs are changing that register on a call to SYS?
