### ISSUE TITLE
MONITOR has issues with memory dump command

### ISSUE THREAD

**Issue by snoopy-f64** [MEGA65/mega65-rom-public#65]
**Test Environment (required)**
 - Platform: XEMU
 - ROM Release: 920383

**Describe the bug**
Using MONITOR the memory dump command seems to ignore the 1st hex digit.

**To Reproduce**
Go to the monitor with MONITOR
Try M 2000 3000 

**Expected behavior**
Showing the memory dump from $2000 to $3000

**Screenshots**
Only one line with dump of $2000 will be shown.

![monitor_bug_a](https://github.com/MEGA65/mega65-rom-public/assets/66867430/c87cabb9-caf2-481e-b365-f620ab60451e)

Tried with ROM 920383.

BTW: The command works fine with the original C65 ROMs (e.g. 911001).

**Comment by snoopy-f64** [comment]
Same issue with the D command (disassemble):

![monitor_bug_b](https://github.com/MEGA65/mega65-rom-public/assets/66867430/67144826-e7d7-49a5-9280-0ce60bb63188)

**Comment by lydon42** [comment]
Perhpas it's no bug but a limitation? The monitor can't show a range bigger than $0FFF as it seems.

**Comment by snoopy-f64** [comment]
It works fine with the original C65-ROMs, so I guess it's an unwanted issue (or bug). ;-)

**Comment by dansanderson** [comment]
The MEGA65 monitor was written from scratch, so it's not so much a regression as an omission. :)

`M 2000 2FFF` works, as does `M 2300 32FF`. Supporting larger ranges or displaying an error message might be an improvement, but this might be a side effect we keep to save code space.

**Comment by snoopy-f64** [comment]
Sorry if I disagree again, but the minimum requirement for me is the original C65 ROM. I see no reason why something should not work in the MEGA65-ROM, which works without problems in the original ROM. A limitation of the output to 4 kB, even without a corresponding message, is a bug for me, if it actually works (in the original ROM).

**Comment by dansanderson** [comment]
I agree it would be a modest improvement. Just from a quick code review, `Mon_Memory` is doing the 32-bit subtraction correctly (`Long_CT` contains the full 32-bit difference), but then using an 8-bit register to count lines, so 256 rows of either 8 or 16 bytes (depending on the screen mode), ignoring the high bits of the subtraction. It just needs a fancier row countdown. Similarly, it looks like `Mon_Disassemble` is only manipulating the lowest byte of `Long_CT`.

**Comment by dansanderson** [comment]
Fixed! https://github.com/MEGA65/mega65-rom/commit/0e7ede5c823d3679cbc6bac8a3b781e7518c19ac
