### ISSUE TITLE
Basic advancement: Use a binary value as string and a string interpretation as byte

### ISSUE THREAD

**Issue by sir-lazarus** [MEGA65/mega65-rom-public#69]
In Mega65-Basic are commands dealing with hex numbers.
E.g. $xxxx is interpreted as a hexadecimal number
and HEX$(x) converts a number to a hex string.

The same commands dealing with binary values would be great.
E.g. %"00000000"  or %00000000 as binary value
and BIN$(x) converts a number to a binary string.

So the following use cases shows  examples:
IF B& = %"00000010" THEN ...

IF B& OR %"00001111" THEN

PRINT "3 AS BIN: ";BIN$(3)

B&=%"100" : B&=B&+2 : PRINT BIN$(B&)

**Comment by dansanderson** [comment]
Implemented. %1001010 is the literal syntax, STRBIN$(num) and DECBIN(str) are the converters.

I chose the names STRBIN$(num) and DECBIN(str) to avoid breaking existing software. Adding keywords is tricky now that people are writing software for the MEGA65. By starting a new keyword with an existing keyword, we assure that the new keyword won't break someone's variable name.

Nevertheless, this needs more testing. I'll do a round of testing with stuff from Filehost before releasing this as a ROM beta, and then others can help me find issues. I reserve the right to rename these functions while it's still in beta, just in case. :)
