### ISSUE TITLE
Syntax error with SETBIT/CLRBIT in connection with IF-THEN-ELSE

### ISSUE THREAD

**Issue by snoopy-f64** [MEGA65/mega65-rom-public#72]
- Platform: Xemu
 - ROM Release: 920385

If you have an IF query and use a SETBIT or CLRBIT in the positive THEN case, then this is thrown out as a syntax error in the THEN case. In the ELSE case it works as it should.

![bit_if_a](https://github.com/MEGA65/mega65-rom-public/assets/66867430/b529b6ea-f894-4b91-b425-10d11eb27ff6)

![bit_if_b](https://github.com/MEGA65/mega65-rom-public/assets/66867430/53b6a7b1-fed1-4076-a170-808b35a8d3ea)

**Comment by sir-lazarus** [comment]
Bevor ELSE a colon was missing which results the syntax error I mean.

**Comment by snoopy-f64** [comment]
> Before ELSE a colon was missing which results the syntax error I mean.

You are right! It's not an error if BASIC 65, it's an error of my own. You always have to put a colon before ELSE.

So issue can be closed. ;⁠-⁠)
