### ISSUE TITLE
"Fixed" address for the IRQ routine?

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-rom-public#76]
Old habits can cause problems. On C64, the locations `$314`/`$315` contains `$EA31`. It was often the case that user wrote a new IRQ routine to do some extra stuff (activated by modifying `$314`/`$315`), and then the routine jumping to `$EA31` to do the "standard" IRQ part. On C65/MEGA65 it seems also the `$314`/`$315` is the location which contains the address of the interrupt handler. However, it seems, the similar role as `$EA31` on C64 changes between different MEGA65 ROM versions now. Which is a problem, since at least one user already tried to rely on that address (yes, it would be better to save the previous content of `$314`/`$315` and use that).

According to a simple `?HEX$(WPEEK($314))` shows, that the displayed address is different between at least '377 and '384 ROM versions. 

My idea here: at least provide a single fixed address (which does not change throughout ROM versions) should/can be provided which is always used to set `$314`/`$315` to avoid confusions when user use a method like above to check which address should `JMP`'ed in their own routine. Surely that "fixed address" can only contains a `JMP $NNNN` in the ROM if the real routine cannot be fixed easily.

Just I fell, `$EA31` in case of C64 is "kind of" a well-known and standard (ok, de-facto standard maybe at max) "entry point" and a similar "standard" can/should be provided for MEGA65 ROMs as well.

Surely, ignore+delete this issue if you don't find it as a useful idea.

**Comment by dansanderson** [comment]
I appreciate the thought. Reading the existing vector before replacing it was always a best practice, even if it wasn't always followed: that allows more than one KERNAL extension to be in memory at the same time. The vectors are the fixed points, not their values, and the default value is not guaranteed to stay the same. It was only a coincidence if $314-5 ever held the same value as on the C64.

Fixing EA31 to always be another JMP instruction to the actual IRQ location would be intrusive. The rest of the KERNAL would have to assemble around it, and organizing code around fixed points is a manual process. It's already a huge pain to work around the few fixed points that are already in the memory layout. (I'd gladly take an assembler that can do that kind of thing automatically, but BSA does not.)

For what it's worth, I've always advocated for the position that we haven't documented features like the KERNAL soft IRQ yet. If people are using them, they are using them at their own peril until we describe them in our own documentation. It's a high priority for me to document them soon. I have an outline and research notes for new chapters that describe hardware and KERNAL interfaces like these, and will recommend best practices for using vectors.
