### ISSUE TITLE
When mounting a Image on Drive 9, Drive 8 gets unmounted

### ISSUE THREAD

**Issue by oe3gwu** [MEGA65/mega65-rom-public#88]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65 R3
 - ROM Release: 920377
 - Core Commit: 3253c5d

**Describe the bug**
When using Drive 8 or Drive 9 as Single Drives, everything works. but if you mount an Image to Drive 8, then mount a different Image to Drive 9, the Image from Drive 8 gets unmounted on my system. I am not able to do a load"$",8 - I get a file not found. Then I readd the Image to Drive 8, then the same happens to Drive 9.

**To Reproduce**
1. Go to C64 Mode (not testet in MEGA65 Mode)
2. Mount Image to Drive 8
3. Load Disk Contents of Drive 8
4. All ok
5. Mount  a new Image to Drive 9
6. Read Directory from Drive 8 again - not working anymore

**Expected behavior**
Drive 8 and Drive 9 should coexist.

**Screenshots**
Currently not available. I try to uplaod them later this week.

**Comment by dansanderson** [comment]
Are you mounting via MOUNT command or Freezer? If MOUNT command, can you provide the specific commands to repro?

If Freezer, it might be a Freezer bug.

**Comment by dansanderson** [comment]
This looks like it might be a Freezer issue so I'm going to file it over in mega65-freezemenu. I can't explain why it's a problem in GO64 mode and not MEGA65 mode, so this might end up back in the mega65-rom-public queue.

Same repro steps stated more specifically:

1. Turn on MEGA65.
2. `GO64`; `YES`
3. Enter Freezer: hold Restore then release.
4. Press 0. Select a D81 disk image.
5. Press F3 to resume. GO64 mode resumes.
6. `LOAD "$",8` then `LIST`. Directory listing of D81 disk image is shown.
7. Enter Freezer: hold Restore then release.
8. Press 1. Select a different D81 disk image.
9. Notice that both unit 8 and unit 9 have a disk image associated.
10. Press F3 to resume. GO64 mode resumes.
11. `LOAD "$",9` then `LIST`. Directory listing of second D81 disk image is shown.
12. `LOAD "$",8`

Expected: First disk image's directory listing is loaded, and can be `LIST`ed.

Actual: `?FILE NOT FOUND  ERROR`, blinking disk light. Re-entering the Freezer shows both disk images are still believed to be mounted.

This does *not* occur if you skip steps 5, 6, and 7 that re-enter the Freezer after the first mount. Entering the Freezer seems to interfere with the mounted images.

This does *not* occur with similar steps in MEGA65 mode, even when using `LOAD "$",8` and `LOAD "$",9`.

**Comment by dansanderson** [comment]
https://github.com/MEGA65/mega65-freezemenu/issues/70
