### ISSUE TITLE
Font Bug - the ultimate Killer

### ISSUE THREAD

**Issue by ruesch** [MEGA65/mega65-rom-public#9]
![IMG_20220528_193727](https://user-images.githubusercontent.com/12908574/170878329-b21e54c4-6748-4f8f-940f-4f17036a30ca.jpg)

> I have made a mistake and typed the following: "FONT X" that kills the M65, also the Freezer shows only the M65 graphics. Only Reset can help.

> Every letter from G to Z used with FONT .... will crash the MEGA65. 

See also: https://www.forum64.de/index.php?thread/126501-font-bug-the-ultimate-killer/

**Comment by Edilbert** [comment]
Thank you for the report.
I've improved the parameter check of the FONT command to accept only A-F.
