### ISSUE TITLE
Preserve auto-insert mode after RUN

### ISSUE THREAD

**Issue by rscottfree** [MEGA65/mega65-rom-public#91]
**Is your feature request related to a problem? Please describe.**
It's a little frustrating that running a basic program disables auto-inert mode (`ESC-A`).

**Describe the solution you'd like**
Auto-insert mode is preserved between runs of a basic program.

**Describe alternatives you've considered**
I'm OK with the the `SHIFT-INST/DEL` method of inserting spaces when needed in the default "overwrite" mode, but I don't see a reason the current behavior should work like it does.

**Additional context**
You can see this behavior by doing `ESC-A`, then typing `RUN` (even with no basic program loaded), and then trying to insert some text inside the `READY.` prompt: The text overwrites instead of inserts.

Appendix B > Escape Sequences > Cursor Behavior also shows that you can type `ESC-E` to set the cursor to non-flashing mode. Unlike the auto-insert mode, this non-flashing cursor mode is preserved after a `RUN`.

**Comment by dansanderson** [comment]
The RUN command resets auto-insert mode before starting the program. I can't say for sure what the intent of the original author was, but it can be shown that it interferes with all printing, not just screen editor typing, which seems like a good reason. Demo:

1. Press ESC-A. Confirm insert mode is on by typing.
2. `PRINT "ABCD{left}{left}XX"` : notice that the PRINT statement honors insert mode, and prints `ABXXCD`.
3. `10 PRINT "ABCD{left}{left}XX"` then `RUN` : notice that insert mode is reset for the program, and prints `ABXX`.

Interestingly, RUN doesn't actually reset very much state, and doesn't seem generally concerned with print system. There is one line of code to address insert mode explicitly, and a comment suggesting that a later author couldn't figure out why it's there:

```asm
    sta _autoinsert ;disable auto-insert mode ?????
```

I can confirm that this is original to the Commodore source code. Neither the code nor the comment are from a change by the MEGA65 team.

I'm inclined to keep it as is. While I'm not against careful changes to the start state, this one could cause confusion by interfering with PRINT statement behavior if the user leaves the cursor in insert mode. Programmers are not accustomed to explicitly updating insert mode in a program as they are for other unexpected state, such as cursor color. If it only affected screen editor typing and not PRINT, I'd be more inclined to preserve the user's requested editor state. This appears to be an intended effect and not a side effect of something else, so it'd be a design change, not a bug fix.

(If you feel strongly, please re-open and I'll poll SteerCo.)

**Comment by rscottfree** [comment]
I rather `PRINT` work in a consistent way than have auto-insert mode remembered after a `RUN`. Thanks for looking into this.
