### ISSUE TITLE
LDQ [$nn],Z is not assembled correctly in the MONITOR

### ISSUE THREAD

**Issue by rscottfree** [MEGA65/mega65-rom-public#94]
**Test Environment (required)**
 - Platform: MEGA65
 - ROM Release: 920839
 - Core Commit: 59bdf5e

**Describe the bug**
In the MONITOR, `LDQ [$10],Z` is translated to `EA B2 10` or `LDA [$10],Z`. Instead it should be `42 42 EA B2 10`.

**To Reproduce**
1. Open `monitor`
2. `D2000` or wherever
3. Type `LDQ [$10],Z` and hit enter
4. See the wrong machine code: `EA B2 10`

**Expected behavior**
The above command should assemble to `42 42 EA B2 10` (when viewing the memory). When disassembling in the monitor I think it would be represented as `*EA B2 10`.

**Additional context**
[This discord post](https://discord.com/channels/719326990221574164/795760112425369610/904382967466573864) suggests that this was fixed in 920236. However, I patched that ROM and tried on dev core 59bdf5e and stable core 93d55f0, and both showed garbage text on the screen. I used M65Connect to patch the rom following the instructions on the filehost, but something could have gone wrong there.

**Comment by johnwayner** [comment]
It looks like 920236 fixed the printing/disassembly of `LDQ [$nn], Z` instructions -- not the assembly of them.
